<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Deg2Rad" Id="{d9219776-8f9f-4ada-a469-1a3633c5aa66}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Deg2Rad : REAL
VAR_INPUT
	fDegIn : REAL; 
END_VAR
VAR
	fRadOut : REAL; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Deg2Rad := fDegIn * (G_VarTask2.fPiVal/180); ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>