<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_FlowControl" Id="{5b7b4cf3-4a9c-4f2d-8ca6-cea1f3c129a8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FlowControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>