<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_PositionControl" Id="{a15dd480-8293-4013-85a3-419a0fe6a27e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PositionControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>