<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_PressureControl" Id="{451dd36a-efcd-4912-a177-4b39ebf3780a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PressureControl
VAR_INPUT
	fPressureVal : REAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fMaxPressure : REAL; 
	bPressureError : BOOL; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>