<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ValveControl" Id="{13a96f09-3b20-4f3b-b174-6aae60c0a541}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ValveControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>